name: Go Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: selfperf/go.mod
          cache-dependency-path: selfperf/go.sum

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            git \
            wget \
            build-essential \
            gcc \
            libc6-dev \
            unzip
          wget https://github.com/capstone-engine/capstone/releases/download/6.0.0-Alpha7/libcapstone-dev_6.0.0-Alpha7_amd64.deb
          sudo dpkg -i libcapstone-dev_6.0.0-Alpha7_amd64.deb

      - name: Fetch LFS files
        run: |
          git lfs install
          git lfs pull
          git lfs checkout

      - name: Run Go tests
        working-directory: selfperf
        run: go test ./...

      - name: Run Go benchmark
        working-directory: selfperf
        run: go test -test.fullpath=true -benchmem -run=^$ -bench ^BenchmarkReportGen$ github.com/paulwuertz/pexplorer/selfperf/cmd/jsonreport
